print_info() {
    info title
    info underline
    info " User" "$USER"
    info "󰇅 Host" "$host"
    info "󰅐 Uptime" "$uptime"
    info " Distro" "$distro"
    info " Term" "$term $term_version"
    info " Shell" "$shell"
    info "󰉉 Disk" "$disk"
    info " Memory" "$memory"
    info "󰩟 Network" "$local_ip ($ip_interface)"
    info cols
}

colors=(blue green yellow red magenta cyan)
bold="on"
underline_enabled="on"
separator=" "
ascii_bold="on"
